steps:
  build:
    image: docker:27-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t antost360/web-shell-client:latest .
    when:
      - event: pull_request
      - event: push
        branch: main

  deploy:
    depends_on: [build]
    image: docker:27-dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/antost/homelab:/home/antost/homelab:ro
    environment:
      DOCKERHUB_PASSWORD:
        from_secret: DOCKERHUB_PASSWORD 
    commands:
      - echo "$DOCKERHUB_PASSWORD" | docker login -u antost360 --password-stdin
      - docker push antost360/web-shell-client:latest
      - cd /home/antost/homelab && docker compose --profile="web-shell-client" up -d web-shell-client 
      - docker image prune -f
    when:
      - event: push
        branch: main

