steps:
  build:
    image: docker:27-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t antost360/web-ssh:latest .
    when:
      - event: pull_request
