services:
  web-ssh:
   extra_hosts:
     - "host.docker.internal:host-gateway"
   build: .
   volumes:
     - web_ssh_config:/app/config/config.json
     - web_ssh_hosts:/app/config/known_hosts


volumes:
  web_ssh_volume:
  web_ssh_hosts:

